encoding: utf-8

# SEO相关信息
title: 武大天协
description: 武汉大学天文爱好者协会
keywords: 武汉大学,武大,天文,天文协会
author: whu-astro
footerText: 'Copyright © 2024 武大天协'

# Copyright © 2024 武大天协

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
# domainUrl: 'https://positron-yao.github.io/positron-yao'
baseurl: 'https://positron-yao.github.io/whu-astro'

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://github.com

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /pages/mainpage
  - title: 活动介绍
    url: /pages/introduction
  - title: 加入我们
    url: /pages/join
  - title: 积分一览
    url: /pages/scores
  - title: 关于
    url: /pages/about

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: TMaize Blog
    url: https://blog.tmaize.net/

